CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    password TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    user_name TEXT UNIQUE NOT NULL,
    address TEXT,
    city TEXT,
    country TEXT,
    phone TEXT,
    website TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    last_login TIMESTAMP
)