CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userName TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL,
    email TEXT NOT NULL,
    address TEXT,
    city TEXT,
    country TEXT,
    phone TEXT,
    website TEXT,
    dateCreated TIMESTAMP DEFAULT now() NOT NULL,
    lastLogin TIMESTAMP
)