CREATE TABLE IF NOT EXISTS bf_messageBoards(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    messageBoardSection INTEGER REFERENCES bf_messageBoard_sections(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL
)