CREATE TABLE IF NOT EXISTS messageBoards(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    messageboard_section INTEGER REFERENCES messageBoard_sections(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT NOT NULL
)