CREATE TABLE IF NOT EXISTS messageBoard_posts(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    board_id INTEGER REFERENCES messageBoards(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    date_posted TEXT NOT NULL,
    likes INTEGER DEFAULT 0,
    users_who_liked INTEGER
)