CREATE TABLE IF NOT EXISTS bf_events(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userId INTEGER REFERENCES bf_users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    location TEXT NOT NULL,
    description TEXT,
    eventDate TEXT NOT NULL,
    eventTime TEXT NOT NULL,
    datePosted TEXT NOT NULL
)