CREATE TABLE IF NOT EXISTS bf_jobs(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    jobCat INTEGER REFERENCES bf_job_cats(id) ON DELETE CASCADE,
    userId INTEGER REFERENCES bf_users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    employment TEXT,
    location TEXT,
    datePosted TEXT NOT NULL
)