CREATE TABLE IF NOT EXISTS jobs(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    job_cat INTEGER REFERENCES job_cats(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    employment TEXT,
    location TEXT,
    contact_name TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    website TEXT,
    date_posted TEXT NOT NULL
)