CREATE TABLE IF NOT EXISTS rentals(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rental_cat INTEGER REFERENCES rental_cats(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    location TEXT,
    price TEXT,
    contact_name TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    airbnb TEXT,
    homeaway TEXT,
    booking_dot_com TEXT,
    other_site TEXT,
    date_posted DATE DEFAULT now() NOT NULL
)