CREATE TABLE IF NOT EXISTS rentals(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rentalCat INTEGER REFERENCES rental_cats(id) ON DELETE CASCADE,
    userId INTEGER REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    location TEXT,
    price TEXT,
    contactName TEXT,
    contactEmail TEXT,
    contactPhone TEXT,
    airbnb TEXT,
    homeAway TEXT,
    bookingDOTcom TEXT,
    otherSite TEXT,
    dateposted DATE DEFAULT now() NOT NULL
)