CREATE TABLE IF NOT EXISTS bf_market_place(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    marketPlaceCat INTEGER REFERENCES bf_market_place_cats(id) ON DELETE CASCADE,
    userId INTEGER REFERENCES bf_users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    location TEXT,
    price TEXT,
    contactName TEXT,
    contactEmail TEXT, 
    contactPhone TEXT,
    dateposted DATE DEFAULT now() NOT NULL
)