CREATE TABLE IF NOT EXISTS market_place(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    market_place_cat INTEGER REFERENCES market_place_cats(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    location TEXT,
    price TEXT,
    contact_name TEXT,
    contact_email TEXT, 
    contact_phone TEXT,
    date_posted DATE DEFAULT now() NOT NULL
)