CREATE TABLE IF NOT EXISTS market_place(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    marketPlaceCat INTEGER REFERENCES market_place_cats(id) ON DELETE CASCADE,
    userId INTEGER REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    location TEXT,
    price TEXT,
    contactName TEXT,
    contactEmail TEXT, 
    contactPhone TEXT,
    dateposted DATE DEFAULT now() NOT NULL
)