CREATE TABLE IF NOT EXISTS directory(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    first_name TEXT,
    last_name TEXT,
    address TEXT,
    city TEXT, 
    state TEXT,
    country TEXT,
    email TEXT,
    phone TEXT,
    website TEXT
)